service:
  name: simple-blog
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 5

functions:
  hello:
    handler: handlers/HelloHandler.hello
    events:
      - http:
          method: get
          path: hello
  post:
    handler: handlers/PostHandler.index
    events:
      - http:
          method: any
          path: post
  user:
    handler: handlers/UserHandler.index
    events:
      - http:
          method: any
          path: user

package:
  individually: true
