service:
  name: simple-blog
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 5

functions:
  hello:
    handler: handlers/HelloHandler.hello
    events:
      - http: GET hello
  post:
    handler: handlers/PostHandler.index
    events:
      - http: GET post
      - http: POST post
      - http: PUT post
      - http: DELETE post
  user:
    handler: handlers/UserHandler.index
    events:
      - http: GET user
      - http: POST user
      - http: PUT user
      - http: DELETE user

package:
  individually: true
