AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: simple-blog Serverless Application Model (SAM) template

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:
  PostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./dist/PostHandler/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /post
            Method: get
        UpdatePost:
          Type: Api
          Properties:
            Path: /post
            Method: put
        SavePost:
          Type: Api
          Properties:
            Path: /post
            Method: post
        DeletePost:
          Type: Api
          Properties:
            Path: /post
            Method: delete
  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/handlers/UserHandler
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        GetUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: get
        UpdateUser:
          Type: Api
          Properties:
            Path: /user
            Method: put
        SaveUser:
          Type: Api
          Properties:
            Path: /user
            Method: post
        DeleteUser:
          Type: Api
          Properties:
            Path: /user
            Method: delete
